version: '3.5'
services:
    # A cada contenedor se le asigna un hostname
    # igual al nombre del servicio
    eureka:
        build: ./eurekaserver
        container_name: eureka_cont
        networks:
            - mynet1
            - mynet2
        ports:
            - 8761:8761

    calculadora:
        build: ./calculadora
        container_name: calculadora_cont
        networks:
            - mynet1
        ports:
            - 8080:8080
        environment:
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
        depends_on:
            - eureka

    sumador:
        # El puerto de sumador no hay que exponerlo,
        # ya que la funcionalidad de sumador se accede desde el contenedor de calculadora

        build: ./sumador

        networks:
            - mynet1
        environment:
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
        depends_on:
            - eureka
            - calculadora

networks:
    default:
        name: mynet
        driver: bridge
    mynet1:
        driver: bridge
    mynet2:
        driver: bridge

volumes:
    m2: