services:
    eureka: 
        build: ./eurekaserver
        container_name: eureka
        networks:
            - mynet1
            - mynet2
        ports:
            - 8761:8761

    calculadora:
        build: ./calculadora
        container_name: calculadora
        networks:
            - mynet1
        ports:
            - 8080:8080
        environment: 
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
        depends_on:
            - "eureka"

    sumador:
        build: ./sumador
        networks:
            - mynet1
        environment: 
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
        depends_on:
            - "eureka"

networks:
    # default:
    #     name: mynet
    #     driver: bridge
    mynet1:
        driver: bridge

    mynet2:
        driver: bridge

    