# En las últimas versiones de docker: docker-compose == docker compose
# Iniciar los servicios: docker compose start
# Detener los servicios: docker compose stop
# Iniciar los servicios, reconstruir imágenes si hay cambios en Dockerfile, mostrar salida por consola: docker compose up
# Ver los logs: docker compose logs -f
# Crear todas las imágenes: docker compose build
# Levantar varias instancias de algún servicio (ej. sumador): docker compose up --scale sumador=3
# Remueve contenedores: docker compose rm -f
version: '3.5'
services:
    # A cada contenedor se le asigna un hostname
    # igual al nombre del servicio
    
    # http://localhost:8761/
    eureka:
        build: ./eurekaserver
        container_name: eureka_cont
        networks:
            - mynet1
            - mynet2
        ports:
            - 8761:8761

    # http://localhost:8080/calculadora/suma?a=5&b=4
    calculadora:
        build: ./calculadora
        container_name: calculadora_cont
        networks:
            - mynet1
        ports:
            - 8080:8080
        environment:
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
        depends_on:
            - eureka

    # El puerto de sumador no hay que exponerlo,
    # ya que la funcionalidad de sumador se accede desde el contenedor de calculadora
    sumador:

        build: ./sumador

        networks:
            - mynet1
        environment:
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
        depends_on:
            - eureka
            - calculadora

networks:
    default:
        name: mynet
        driver: bridge
    mynet1:
        driver: bridge
    mynet2:
        driver: bridge

volumes:
    m2:
